### ISSUE TITLE
add: About ものづくりに対する思い

### ISSUE THREAD

**Issue by oratake** [hinaken/hinaken_official#20]
担当ポエムを書く

画像はこれ
![making](https://user-images.githubusercontent.com/3185871/90633863-c8fdc200-e261-11ea-8a2e-b389b1f17c0e.jpg)

**Comment by oratake** [comment]
下書

ものづくりの根源の一つとして、現状に満足せず常に改善しつづけようという向上心があると考えています。
生活している中で感じる不便や違和感、欲求などを、ものづくりという形で昇華してゆくのです。
このとき手段は問題ではありません。実現可能な方法が手元にないとしても、その方法を模索し続けることが、ものづくりの発展に繋がります。
また、ものづくりもまた、試行錯誤の結果が新しいものづくりへと繋がっていきます。
ですから、私たちは問い続けます。「ない？だったら、つくろう」と

**Comment by ShoutaWATANABE** [comment]
> 下書
> 
> ものづくりの根源の一つとして、現状に満足せず常に改善しつづけようという向上心があると考えています。
> 生活している中で感じる不便や違和感、欲求などを、ものづくりという形で昇華してゆくのです。
> このとき手段は問題ではありません。実現可能な方法が手元にないとしても、その方法を模索し続けることが、ものづくりの発展に繋がります。
> また、こうして成し遂げられたものづくりもまた、新しいものづくりへと繋がる布石になると確信しています。
> ですから、私たちは問い続けます。 **「ない？だったら、つくろう」** と

**Comment by ShoutaWATANABE** [comment]
👍

**Comment by oratake** [comment]
この文章でmdぶっこんでいく

**Comment by oratake** [comment]
やったぜ。
