### ISSUE TITLE
request:プロフィール画像変更依頼

### ISSUE THREAD

**Issue by ayareily** [hinaken/hinaken_official#26]
ごめんなさい，[twitterの画像](https://twitter.com/ayareily/photo)に変えてください（暇な時で大丈夫です）

**Comment by oratake** [comment]
https://pbs.twimg.com/profile_images/1234863518010298374/t5AoKvXG_400x400.jpg

コイツも直接やっていいものか迷うな

**Comment by ShoutaWATANABE** [comment]
@oratake 
いま触っても大丈夫そうだから、大丈夫じゃね

**Comment by oratake** [comment]
@ShoutaWATANABE あーいや、このURLは永続的なもんなのかなと

**Comment by ShoutaWATANABE** [comment]
@oratake 
だから、発行されてから何時間も経っても見れたから、大丈夫じゃね？と

**Comment by oratake** [comment]
@ShoutaWATANABE あーなるほどそういうことね。Slackbotの画像もだいたいそのままだし、いいか
